apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.environment }}
  labels:
    app: {{ .Values.app.name }}-{{ .Values.app.environment }}
    group: {{ .Values.app.group }}
spec:
  replicas: {{ .Values.app.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}-{{ .Values.app.environment }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}-{{ .Values.app.environment }}
        group: {{ .Values.app.group }}
      annotations:
          vault.hashicorp.com/agent-inject: 'true'
          vault.hashicorp.com/role: '{{ .Values.app.name }}-{{ .Values.app.environment }}'
          vault.hashicorp.com/agent-inject-secret-secrets.txt: 'services/staging/users-service'
          vault.hashicorp.com/agent-inject-template-secrets.txt: |
            {{`{{- with secret "services/staging/users-service" }}
            {{- range $k, $v := .Data.data }}
            export {{ $k }}={{ $v }}
            {{- end }}
            {{- end }} `}}
    spec:
      serviceAccountName: {{ .Values.app.name }}-{{ .Values.app.environment }}
      containers:
        - name: {{ .Values.app.name }}-{{ .Values.app.environment }}
          image: {{ .Values.app.container.image.repository }}:{{ .Values.app.container.image.tag }}
          ports:
            - containerPort: {{ .Values.app.container.port }}
          # env:
          #   {{- range $key := .Values.app.container.env }}
          #   - name: {{ $key }}
          #     valueFrom:
          #       secretKeyRef:
          #         name: users-service-staging
          #         key: {{ $key }}
          #   {{- end }}
      {{- with .Values.app.container.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
