{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-{{ .environment }}
  labels:
    app: {{ .name }}-{{ .environment }}
    codebase: {{ .codebase }}
spec:
  {{ if not .autoscaling }}
  # Do not set a replica count if autoscaling is enabled
  # https://technologyconversations.com/2018/10/10/to-replicas-or-not-to-replicas-in-kubernetes-deployments-and-statefulsets/
  replicas: {{ required "replicaCount is required if autoscaling is disabled" .replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app: {{ .name }}-{{ .environment }}
  template:
    metadata:
      labels:
        app: {{ .name }}-{{ .environment }}
        group: {{ .group }}
      annotations:
          rollme: {{ randAlphaNum 5 | quote }}
    spec:
      serviceAccountName: {{ .codebase }}-{{ .environment }}
      containers:
        - name: {{ .name }}-{{ .environment }}
          image: {{ .container.image.repository }}:{{ .container.image.tag }}
          ports:
            - containerPort: {{ .container.port }}
          readinessProbe: {{ toYaml .container.readinessProbe | nindent 12 }}
          resources: {{ toYaml .container.resources | nindent 12 }}
          volumeMounts: {{ toYaml .container.volumeMounts | nindent 12 }}
          env:
            {{- range .container.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
            - name: KUBERNETES
              value: 'true'
            - name: PULL_SECRETS_FROM_VAULT
              value: '1'
            - name: VAULT_ADDR
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: address
            - name: VAULT_TOKEN
              valueFrom:
                secretKeyRef:
                  name: vault
                  key: token
            - name: APP_ENV
              value: {{ .environment }}
      {{- with .volumes }}
      volumes:
        {{- toYaml . | nindent 8}}
      {{- end }}
      {{- with .container.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
---
{{- end }}
