{{- range .Values.apps }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}-{{ .environment }}
  labels:
    app: {{ .name }}-{{ .environment }}
    group: {{ .group }}
spec:
  replicas: {{ .replicaCount }}
  selector:
    matchLabels:
      app: {{ .name }}-{{ .environment }}
  template:
    metadata:
      labels:
        app: {{ .name }}-{{ .environment }}
        group: {{ .group }}
      annotations:
          rollme: {{ randAlphaNum 5 | quote }}
          vault.hashicorp.com/agent-inject: 'true'
          vault.hashicorp.com/role: '{{ .name }}-{{ .environment }}'
          vault.hashicorp.com/agent-inject-secret-secrets.txt: 'services/{{ .environment }}/{{ .name }}'
          vault.hashicorp.com/agent-inject-template-secrets.txt: |
            {{ "{{" }}- with secret "services/{{ .environment }}/{{ .name }}" {{ "}}" }}
            {{ "{{" }}- range $k, $v := .Data.data {{ "}}" }}
            export {{ "{{" }} $k {{ "}}" }}="{{ "{{" }} $v {{ "}}" }}"
            {{ "{{" }}- end {{ "}}" }}
            {{ "{{" }}- end {{ "}}" }}
    spec:
      serviceAccountName: {{ .name }}-{{ .environment }}
      containers:
        - name: {{ .name }}-{{ .environment }}
          image: {{ .container.image.repository }}:{{ .container.image.tag }}
          ports:
            - containerPort: {{ .container.port }}
          env:
            - name: KUBERNETES
              value: 'true'
            - name: VAULT_ADDR
              value: 'TODO'
            - name: VAULT_TOKEN
              value: 'TODO'
            - name: PYPI_INDEX_URL
              value: 'TODO'
            - name: PULL_SECRETS_FROM_VAULT
              value: '1'
            - name: APP_ENV
              value: {{ .environment }}
            {{- range .container.env }}
            - name: {{ .name }}
              value: {{ .value }}
            {{- end }}
      {{- with .container.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
