{{- range .Values.apps }}
{{- if .service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-{{ .environment }}
  labels:
    group: {{ .group }}
    {{- if not .service }}
    sidecar.istio.io/inject: "false"
    {{- end }}
  {{ if eq .service.type "LoadBalancer" }}
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: {{ .service.loadBalancerID }}
  {{- end }}
spec:
  type: {{ .service.type }}
  selector:
    app: {{ .name }}-{{ .environment }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .container.port }}
      {{ if .service.name }}
      name: {{ .service.name }}
      {{- end }}
      {{ if .service.protocol }}
      protocol: {{ .service.protocol }}
      {{- end }}
      {{ if .service.externalIPs }}
      externalIPs:
        {{- range .service.externalIPs }}
        - {{ . }}
        {{- end }}
      {{- end }}
      {{ if eq .service.type "NodePort" }}
      nodePort: {{ .service.nodePort }}
      {{- end }}
---
{{- end }}
{{- end }}
