{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-{{ .environment }}
  labels:
    group: {{ .group }}
  {{ if eq .service.type "LoadBalancer" }}
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: {{ .service.loadBalancerID }}
  {{- end }}
spec:
  type: {{ .service.type }}
  selector:
    app: {{ .name }}-{{ .environment }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .container.port }}
      {{ if eq .service.type "NodePort" }}
      nodePort: {{ .service.nodePort }}
      {{- end }}
---
{{- end }}
