{{- range .Values.apps }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}-{{ .environment }}
  labels:
    group: {{ .group }}
spec:
  type: {{ .service.type }}
  selector:
    app: {{ .name }}-{{ .environment }}
  ports:
    - port: {{ .service.port }}
      targetPort: {{ .container.port }}
{{- end }}
