apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-{{ .Values.app.environment }}
  labels:
    group: {{ .Values.app.group }}
spec:
  type: {{ .Values.app.service.type }}
  selector:
    app: {{ .Values.app.name }}-{{ .Values.app.environment }}
  ports:
    - port: {{ .Values.app.service.port }}
      targetPort: {{ .Values.app.container.port }}
