apps:
  - name: product-service-api
    environment: production
    codebase: product-service
    replicaCount: 1
    container:
      image:
        repository: product-service-api
        tag: latest
      port: 80
      env: []
      imagePullSecrets: []
      readinessProbe:
        httpGet:
          path: /_health
          port: 80
        initialDelaySeconds: 5
        periodSeconds: 10
        timeoutSeconds: 1
        successThreshold: 1
        failureThreshold: 3
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 200m
    service:
      type: ClusterIP
      port: 80

  - name: product-service-worker
    environment: production
    codebase: product-service
    replicaCount: 1
    container:
      image:
        repository: product-service-worker
        tag: latest
      port: 80
      env: []
      imagePullSecrets: []
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 200m
    service:
      type: ClusterIP
      port: 80

cronjobs:
  - name: product-worker-cronjob
    environment: production
    codebase: product-service
    schedule: "*/5 * * * *"
    container:
      image:
        repository: product-worker-cronjob
        tag: latest
      imagePullSecrets: []
      command: "python -m app.worker"
      resources:
        limits:
          cpu: 500m
        requests:
          cpu: 200m
      env: []
