apps:
  - name: product-service-api
    environment: production
    codebase: product-service
    replicaCount: 1
    container:
      image:
        repository: product-service-api
        tag: latest
      port: 80
      env: []
      imagePullSecrets: []
    hostNetworkEnabled: false
    service:
      type: ClusterIP
      port: 80

  - name: product-service-worker
    environment: production
    codebase: product-service
    replicaCount: 1
    container:
      image:
        repository: product-service-worker
        tag: latest
      port: 80
      env: []
      imagePullSecrets: []
    hostNetworkEnabled: false
    service:
      type: ClusterIP
      port: 80
