app:
  name: app
  environment: staging
  group: app
  replicaCount: 1
  container:
    image:
      repository: application-backend
      tag: latest
    imagePullSecrets: []
    port: 80
    config: []
  service:
    type: ClusterIP
    port: 80
